### ISSUE TITLE
Can't open craig-willis-dataverse-binder-hynnlymg notebook

### ISSUE THREAD

**Issue by pdurbin** [craig-willis/dataverse-binder#1]
Hi! I'm entering via https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/edit?usp=sharing

The README says "Now, open in it in Binder using this repo: [thalpbblackaff.tab](https://hub.mybinder.org/user/craig-willis-dataverse-binder-hynnlymg/notebooks/dataverse.ipynb?fileId=2865473&siteUrl=https://dataverse.harvard.edu)" and I tried but I get this error:

<img width="1040" alt="screen shot 2018-11-21 at 5 55 42 pm" src="https://user-images.githubusercontent.com/21006/48872397-e95fca80-edb6-11e8-822d-82486ccb5f77.png">

Is this expected?

**Comment by craig-willis** [comment]
Should be fixed now

**Comment by pdurbin** [comment]
Yes! 14f3b51 seems to have fixed it. Thanks, @craig-willis ! Closing.
